steps:
# Costruisci l'immagine container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA', '.'] 

# Esegui il push dell'immagine container a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA']

# Esegui il deployment dell'immagine container su Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - pantry-tracker-service # Questo sarà il nome del tuo servizio Cloud Run
  - --image
  - gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA
  - --region
  - europe-west1 # Questa sarà la regione dove verrà deployato il tuo servizio
  - --platform=managed
  # - --allow-unauthenticated # Decommenta questa riga se l'applicazione deve essere accessibile pubblicamente
  env:
  - PROJECT_ID=$PROJECT_ID

images:
- gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA

substitutions:
  _SERVICE_NAME: pantry-tracker-service # Il nome del tuo servizio Cloud Run
  _REGION: europe-west1                 # La tua regione GCP
