steps:
# Costruisci l'immagine container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA', '.'] 

# Esegui il push dell'immagine container a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA']

# Esegui il deployment dell'immagine container su Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - pantry-tracker-service # Nome del servizio Cloud Run
  - --image
  - gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA
  - --region
  - europe-west1 # Regione di deployment
  - --platform=managed
  # - --allow-unauthenticated # DECOMMENTARE SE L'APP FLUTTER NON USA AUTENTICAZIONE


images:
- gcr.io/$PROJECT_ID/pantry-tracker-service:$COMMIT_SHA

substitutions:
  _SERVICE_NAME: pantry-tracker-service # Il nome del tuo servizio Cloud Run
  _REGION: europe-west1                 # La tua regione GCP
# ... (il resto del tuo cloudbuild.yaml) ...

options:
  logging: CLOUD_LOGGING_ONLY
